### ISSUE TITLE
Code snapshot for shader code

### ISSUE THREAD

**Issue by MrEliptik** [fenix-hub/godot-engine.code-snapshot#13]
Hey, first of all, thanks for your work, I love the idea!

I was wondering how hard it would be to implement the same thing but for shader code? I don't know exactly how you did it right now, but I believe you use the syntax server of Godot. That should be relatively easy to implement? If so, I could take a look and make a PR for it if you don't want to do it.

Cheers

**Comment by fenix-hub** [comment]
Hi @MrEliptik 
As far as Godot APIs expose the Shader Text editor (like they currently do with the ScriptEditor), nothing is impossible.
I'd just need to check that, and a code-snapshot for shaders would be pretty easy to implement.
Highlighting is not currently using any syntax server, I just highlight Godot keywords and types.
The code may not me that much ordered, but is very easy to access.

**Comment by fenix-hub** [comment]
@MrEliptik little update,
I was not able to find anything regarding the ShaderScriptEditor.
I've asked if there's something like [this](https://docs.godotengine.org/it/stable/classes/class_scripteditor.html) for shaders. Eventually I'll contact the devs or open an issue.

**Comment by MrEliptik** [comment]
I've also checked and can't find anything exposed in GDScript. I'll ask some people also to see if there's a workaround.
