### ISSUE TITLE
Parse Error: The identifier "CodeSnapshotInstance" isn't a valid type (not a script or class), or couldn't be found on base "self".

### ISSUE THREAD

**Issue by Hotklou2404** [fenix-hub/godot-engine.code-snapshot#14]
Trying to activate the plugin results in this error, and the plugin being deactivated:
> * res://addons/code-snapshot/plugin.gd:6 - Parse Error: The identifier "CodeSnapshotInstance" isn't a valid type (not a script or class), or couldn't be found on base "self".
> * modules/gdscript/gdscript.cpp:566 - Method failed. Returning: ERR_PARSE_ERROR

For reference, I'm on Windows 10, I'm using Godot Engine v3.4.2.stable.official.45eaa2daf, and I'm using v1.5 of this plugin. And I let the plugin install automatically into the addons folder (I did not do a manual installation).

**Comment by fenix-hub** [comment]
Could not reproduce in the same environment sadly.
Try reloading the project or removing the `: CodeSnapshotInstance` in plugin.gd  > line 6 and reloading.
