### ISSUE TITLE
Screenshot crop: doesn't take "editor/display_scale" into account? 

### ISSUE THREAD

**Issue by davcri** [fenix-hub/godot-engine.code-snapshot#5]
The first screenshot was taken with the default Godot interface scaling.  
The second screenshot was taken with `Editor -> Editor settings -> Display Scale` set to 150%.

![screenshot](https://user-images.githubusercontent.com/6860637/103766282-da801480-501e-11eb-844d-30485b65efc1.png)

---

![screenshot-scale150%](https://user-images.githubusercontent.com/6860637/103766292-dce26e80-501e-11eb-826b-00fed2b4ece5.png)

**Comment by fenix-hub** [comment]
Hi @davcri ,
Thank you for submitting this issue.
#6 will fix this adding a CodeSnpashot viewport and making it completely indipendent from editor settings.
Eventually, CodeSnapshot font size will be configurable as a separate setting keeping it indipendent from editor's one.
Close this issue whenever you want, I'll leave it open if you want to suggest other changes related to this issue.
